# Generated by Django 3.2.12 on 2022-03-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Movie_Success', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieName', models.CharField(default=None, max_length=100)),
                ('MovieProducer', models.CharField(default=None, max_length=100)),
                ('MovieDirector', models.CharField(default=None, max_length=100)),
                ('MovieActor', models.CharField(default=None, max_length=100)),
                ('MovieActress', models.CharField(default=None, max_length=100)),
                ('MovieMusic', models.CharField(default=None, max_length=100)),
                ('MarketBudget', models.CharField(default=None, max_length=100)),
                ('Date', models.CharField(default=None, max_length=100)),
                ('SuccessStatus', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'MovieData',
            },
        ),
    ]
