# Generated by Django 3.2.12 on 2022-03-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Movie_Success', '0003_moviedata_moviewriter'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='MovieGenre',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
