# Generated by Django 3.2.12 on 2022-03-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Movie_Success', '0004_moviedata_moviegenre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviedata',
            old_name='Date',
            new_name='Day',
        ),
        migrations.AddField(
            model_name='moviedata',
            name='Year',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
